## HW7 P1
### mahsa amini 9817823

In [1]:
import numpy as np

### sample

In [2]:
boys_pref = np.array([[1,2,4,3], [1,2,3,4], [3,1,2,4], [2,3,1,4]])

In [3]:
girls_pref = np.array([[3,4,1,2], [2,3,4,1], [1,2,3,4], [3,4,2,1]])

In [4]:
boys_pref

array([[1, 2, 4, 3],
       [1, 2, 3, 4],
       [3, 1, 2, 4],
       [2, 3, 1, 4]])

In [5]:
girls_pref

array([[3, 4, 1, 2],
       [2, 3, 4, 1],
       [1, 2, 3, 4],
       [3, 4, 2, 1]])

In [6]:
def checking_preference(girl1, girl2, boy_num, boy_pref):
    for i in range(0,boy_pref.shape[1]):
        if boy_pref[boy_num-1,i]==girl1:
            girl1_rank= i
        if boy_pref[boy_num-1,i]==girl2:
            girl2_rank= i

    if girl1_rank < girl2_rank:
        res =1
    else:
        res = 0
        
    return res

In [7]:
def stable_marriage(boys_pref, girls_pref):
    
    num = girls_pref.shape[0]
    proposed = np.zeros(num)
    engaged = np.zeros(num)
    
    for i in range(0, num):
        engaged[i] = -1
        
    while (1) : 
        count = 0
        for i in range(0,num):
            if(proposed[i]==1):
                count+=1
        if(count == num):
            return engaged
        for i in range(0, num):
            if proposed[i]!=1:
                for j in range(0, girls_pref.shape[1]):
                    if proposed[i]!=1:
                        g_pref = girls_pref[i,j]
                        if engaged[g_pref-1]==-1:
                            engaged[g_pref-1]=i+1
                            proposed[i] = 1
                        else:
                            check= checking_preference(i+1, engaged[g_pref-1], g_pref,boys_pref)
                            if (check):
                                prev = engaged[g_pref-1]
                                engaged[g_pref-1]=i+1
                                proposed[i]=1
                                temp = int(prev - 1)
                               
                                proposed[temp] = 0
                                
     
    
    return engaged
        

In [8]:
stable_marriage(boys_pref, girls_pref)

array([3., 2., 1., 4.])